export const REACT_APP_AUTH0_DOMAIN = "dev-41w2hma5.us.auth0.com";
export const REACT_APP_AUTH0_CLIENT_ID = "R5yaPdIdH7RTKefI1Nf255ddwAIrzfqI";
// export const REACT_APP_AUTH0_AUDIENCE = "https://codedependent.com/api";
// export const SERVER_URL = "http://localhost:6060";
export const SERVER_URL = "http://localhost:4000";
// REACT_APP_AUTH0_DOMAIN=YOUR-AUTH0-DOMAIN
// REACT_APP_AUTH0_CLIENT_ID=YOUR-AUTH0-APP-CLIENT-ID
// REACT_APP_AUTH0_AUDIENCE=https://codedependent.com/api
// REACT_APP_SERVER_URL=http://localhost:6060
